ALTER TABLE `user`
  ADD COLUMN IF NOT EXISTS `recovery_code` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `failed_login_attempts` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `locked_until` INT DEFAULT NULL;
